### ISSUE TITLE
Can you avoid using eval?

### ISSUE THREAD

**Issue by vjeux** [lwansbrough/react-native-markdown#1]
Using eval on user generated content is _extremely_ dangerous. Can you instead change the renderer to output React nodes instead? Here's an example where I forked Marked and output web React nodes. I think that it wouldn't be really hard to replace it with React Native nodes instead.

https://github.com/facebook/react-native/blob/master/website/core/Marked.js

**Comment by lwansbrough** [comment]
Agreed. Done! I actually decided to change the Markdown parser in favour of a more extensible one.

**Comment by vjeux** [comment]
Nice!
