### ISSUE TITLE
Custom styling in example usage

### ISSUE THREAD

**Issue by pdilyard** [lwansbrough/react-native-markdown#10]
I'm new to react and was wondering if I could get a code example of custom styling. I've tried this so far:

``` jsx
<Markdown text={styles.text}>
  Some *really* basic **Markdown**.
</Markdown>
```

But to no avail. It would be nice if there was an example of styling in the documentation.

**Comment by lwansbrough** [comment]
``` jsx
<Markdown style={styles}>
  Some *really* basic **Markdown**.
</Markdown>
```

is probably what you're looking for!

**Comment by pdilyard** [comment]
Great, thanks!
